const {PGlite}=require('@electric-sql/pglite');const assert=require('node:assert/strict');const fs=require('node:fs');
const db=new PGlite();const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
(async()=>{
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
    create table companies(id uuid primary key,slug text,active boolean);
    create table profiles(id uuid primary key,active boolean,platform_role text);
    create table company_members(company_id uuid,profile_id uuid,active boolean,company_role text);
    grant usage on schema public to service_role;
    grant select on companies,profiles,company_members to service_role;`);
  await db.query("insert into companies values($1,'xpace',true),($2,'school',true)",[id(1),id(2)]);
  await db.query("insert into profiles values($1,true,'platform_owner'),($2,true,'company_manager'),($3,true,'company_manager'),($4,false,'company_manager')",[id(3),id(4),id(5),id(6)]);
  await db.query("insert into company_members values($1,$2,true,'manager'),($3,$4,true,'manager')",[id(2),id(4),id(1),id(5)]);
  // Model Supabase legacy defaults, not just an empty PostgreSQL installation.
  await db.exec('alter default privileges in schema public grant all on tables to anon,authenticated,service_role; alter default privileges in schema public grant all on sequences to anon,authenticated,service_role;');
  await db.exec(fs.readFileSync('supabase/migrations/20261001225412_saas_commercial_preparation.sql','utf8'));
  const book=(await db.query('select id,config from saas_pricebooks')).rows[0];assert.equal(book.config.addons.WHATSAPP,15000);
  assert.equal((await db.query('select count(*)::int n from saas_order_drafts')).rows[0].n,0);
  await assert.rejects(db.query("update saas_commercial_settings set phase='ACTIVE'"));
  await db.exec('set role service_role');
  await db.query("insert into saas_payment_account_drafts(tenant_company_id,created_by,account_mode) values($1,$2,'PARENT')",[id(1),id(3)]);
  await assert.rejects(db.query("insert into saas_payment_account_drafts(tenant_company_id,created_by,account_mode) values($1,$2,'PARENT')",[id(2),id(4)]),/MODE_INVALID/);
  await db.query("insert into saas_payment_account_drafts(tenant_company_id,created_by,account_mode) values($1,$2,'SUBACCOUNT')",[id(2),id(4)]);
  const quote={exempt:false,accountMode:'SUBACCOUNT',monthlyCents:null,canCharge:false,kind:'SIMULATION'};
  const save=async(actor=id(4),request=id(10),fingerprint='a'.repeat(64),q=quote)=>(await db.query('select (saas_save_order_draft($1,$2,$3,$4,$5,$6)).id id',[id(2),actor,request,fingerprint,book.id,q])).rows[0].id;
  const order=await save();assert.equal(await save(),order);
  await assert.rejects(save(id(4),id(10),'b'.repeat(64)),/IDEMPOTENCY_CONFLICT/);
  await assert.rejects(save(id(5),id(11)),/ACCESS_DENIED/);await assert.rejects(save(id(6),id(12)),/ACCESS_DENIED/);
  await assert.rejects(save(id(4),id(13),'a'.repeat(64),{...quote,exempt:true,accountMode:'PARENT'}),/EXEMPTION_INVALID/);
  await assert.rejects(db.query("update saas_order_drafts set status='ACTIVE'"));
  await assert.rejects(db.query("update saas_pricebooks set config='{}'"));
  await db.exec('reset role');
  await assert.rejects(db.query("update saas_pricebooks set config='{}'"),/SNAPSHOT_IMMUTABLE/);
  await assert.rejects(db.query("delete from saas_order_drafts"),/SNAPSHOT_IMMUTABLE/);
  assert.equal((await db.query('select count(*)::int n from saas_order_drafts')).rows[0].n,1);
  await db.exec('set role service_role');
  await db.query("insert into saas_billing_preferences(tenant_company_id,payment_method,addons,updated_by) values($1,'PIX',array['WHATSAPP'],$2)",[id(2),id(4)]);
  await db.query("update saas_billing_preferences set payment_method='CREDIT_CARD' where tenant_company_id=$1",[id(2)]);
  await assert.rejects(db.query("update saas_billing_preferences set status='ACTIVE'"));
  await assert.rejects(db.query("update saas_billing_preferences set addons=array['FAKE']"));
  await assert.rejects(db.query("insert into saas_order_drafts(tenant_company_id,created_by,request_id,fingerprint,pricebook_id,quote) values($1,$2,$3,$4,$5,'{}')",[id(2),id(4),id(17),'a'.repeat(64),book.id]));
  await db.exec('reset role');
  for(const role of ['anon','authenticated']){await db.exec('set role '+role);for(const table of ['saas_pricebooks','saas_order_drafts','saas_commercial_settings','saas_whatsapp_connections','saas_payment_account_drafts','saas_billing_preferences','saas_billing_invoices'])await assert.rejects(db.query('select * from '+table),/permission denied/);await assert.rejects(save(),/permission denied/);await db.exec('reset role');}
  const secured=await db.query("select relname,relrowsecurity from pg_class where relname like 'saas_%' and relkind='r'");assert.equal(secured.rows.length,7);assert.ok(secured.rows.every(row=>row.relrowsecurity));
  await db.exec('set role service_role');
  await assert.rejects(db.query('select saas_save_pricebook($1,$2,$3)',[id(4),book.id,book.config]),/ACCESS_DENIED/);
  const revision=(await db.query('select (saas_save_pricebook($1,$2,$3)).revision r',[id(3),book.id,book.config])).rows[0].r;
  assert.equal(Number(revision),2);
  await assert.rejects(db.query('select saas_save_pricebook($1,$2,$3)',[id(3),book.id,book.config]),/PRICEBOOK_CONFLICT/);
  await db.exec('reset role');
  await db.exec(fs.readFileSync('supabase/migrations/20261001230148_saas_sandbox_operation_guard.sql','utf8'));
  await db.exec('set role service_role');
  const begin=async(actor=id(3),kind='CREATE_SUBACCOUNT',fingerprint='c'.repeat(64))=>(await db.query('select saas_begin_sandbox_operation($1,$2,$3,$4) result',[id(2),actor,kind,fingerprint])).rows[0].result;
  const lease=await begin();assert.equal(lease.acquired,true);assert.equal((await begin()).acquired,false);
  await assert.rejects(begin(id(4)),/ACCESS_DENIED/);await assert.rejects(begin(id(3),'CREATE_SUBACCOUNT','d'.repeat(64)),/INPUT_CONFLICT/);
  await assert.rejects(db.query("select saas_finish_sandbox_operation($1,$2,'SUCCEEDED','{}')",[lease.id,id(9)]),/LEASE_INVALID/);
  await db.query("select saas_finish_sandbox_operation($1,$2,'UNKNOWN',null)",[lease.id,lease.leaseKey]);assert.equal((await begin()).status,'UNKNOWN');assert.equal((await begin()).acquired,false);
  const sub=await begin(id(3),'CREATE_SUBSCRIPTION');await db.query("select saas_finish_sandbox_operation($1,$2,'SUCCEEDED','{}')",[sub.id,sub.leaseKey]);assert.equal((await begin(id(3),'CREATE_SUBSCRIPTION')).status,'SUCCEEDED');
  await assert.rejects(db.query("select saas_finish_sandbox_operation($1,$2,'UNKNOWN',null)",[sub.id,sub.leaseKey]),/LEASE_INVALID/);
  await db.exec('reset role');await db.query("delete from saas_sandbox_operations where id=$1",[lease.id]);const expired=await begin();await db.query("update saas_sandbox_operations set lease_until=now()-interval '1 minute' where id=$1",[expired.id]);assert.equal((await begin()).status,'UNKNOWN');
  await db.exec('set role authenticated');await assert.rejects(db.query('select * from saas_sandbox_operations'),/permission denied/);await assert.rejects(begin(),/permission denied/);await db.exec('reset role');
  assert.equal((await db.query("select has_table_privilege('service_role','saas_billing_invoices','INSERT') p")).rows[0].p,true);
  await db.exec(fs.readFileSync('supabase/migrations/20261001234305_saas_least_privilege.sql','utf8'));
  for (const table of ['saas_commercial_settings','saas_billing_invoices']) {
    const privileges=(await db.query("select has_table_privilege('service_role',$1,'SELECT') r,has_table_privilege('service_role',$1,'INSERT') i,has_table_privilege('service_role',$1,'UPDATE') u,has_table_privilege('service_role',$1,'DELETE') d,has_table_privilege('service_role',$1,'TRUNCATE') t",[table])).rows[0];
    assert.deepEqual(privileges,{r:true,i:false,u:false,d:false,t:false});
  }
  assert.equal((await db.query("select has_sequence_privilege('service_role','saas_pricebooks_revision_seq','UPDATE') p")).rows[0].p,false);
  for(const table of ['saas_pricebooks','saas_order_drafts','saas_payment_account_drafts','saas_whatsapp_connections','saas_billing_preferences','saas_sandbox_operations']) {
    assert.equal((await db.query("select has_table_privilege('service_role',$1,'DELETE') p",[table])).rows[0].p,false);
    assert.equal((await db.query("select has_table_privilege('service_role',$1,'TRUNCATE') p",[table])).rows[0].p,false);
  }
  await db.exec('set role service_role');
  await assert.rejects(db.query('update saas_commercial_settings set singleton=singleton'),/permission denied/);
  await assert.rejects(db.query('insert into saas_billing_invoices default values'),/permission denied/);
  await assert.rejects(db.query('delete from saas_sandbox_operations'),/permission denied/);
  await db.query("update saas_billing_preferences set payment_method='PIX' where tenant_company_id=$1",[id(2)]);
  await save();
  const latest=(await db.query('select id from saas_pricebooks order by revision desc limit 1')).rows[0].id;
  await db.query('select saas_save_pricebook($1,$2,$3)',[id(3),latest,book.config]);
  await db.exec('reset role');
  await db.close();console.log('SaaS isolated PostgreSQL: preparation only, immutable versions, account modes, privacy, authorization, exemption, idempotency and least privileges with Supabase defaults passed.');
})().catch(async e=>{console.error(e);await db.close();process.exitCode=1;});
