const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n]||require(n),Request,Response,URL,Date,Set,process:{env:{}},console:{error(){}}});return exports;}
class AccessError extends Error{constructor(message,status){super(message);this.status=status;}}
const rules=load('lib/saas/commercial.ts',{});const preferences=load('lib/saas/billing-preferences.ts',{'./commercial':rules});
const rpc=load('lib/saas/rpc-row.ts',{});
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function fixture(role='company_manager',company=id(2)){
 const calls=[],writes=[];const book={id:id(8),revision:1,config:{...rules.emptyPricebook(),whatsappCostCents:10000}};
 const results={saas_commercial_settings:{data:{owner_company_id:id(1),phase:'PREPARATION'}},saas_pricebooks:{data:book},saas_order_drafts:{data:[]},saas_payment_account_drafts:{data:null},saas_whatsapp_connections:{data:null},saas_billing_preferences:{data:{payment_method:'PIX',addons:['WHATSAPP'],status:'PREPARATION'}},xpace_people:{data:null,count:51},saas_billing_invoices:{data:[],count:0}};
 const admin={from(table){const filters=[];const builder={};for(const method of ['select','eq','order','range','limit','maybeSingle','single','upsert','insert'])builder[method]=(...args)=>{calls.push({table,method,args});if(method==='eq')filters.push(args);if(['insert','upsert'].includes(method))writes.push({table,body:args[0]});return builder;};builder.then=(ok,fail)=>Promise.resolve(results[table]||{data:null}).then(ok,fail);return builder;},async rpc(name,input){writes.push({name,body:input});return{data:{id:id(9),quote:input.p_quote}};}};
 const access={admin,company:{id:company,slug:'school',name:'School'},profile:{platform_role:role},user:{id:id(4)}};
 const imports={'next/server':{NextResponse:Response},'@/lib/saas/rpc-row':rpc,'@/lib/saas/commercial':rules,'@/lib/saas/billing-preferences':preferences,'@/lib/server/company-access':{AccessError,requireCompanyAccess:async(request,slug)=>{if(request.headers.get('authorization')!=='Bearer fixture')throw new AccessError('SESSION',401);if(slug!=='school')throw new AccessError('TENANT',403);return access;}}};
 return{calls,writes,store:load('app/api/saas/store/route.ts',imports),plan:load('app/api/saas/plan/route.ts',imports),request(body,slug='school',token='fixture'){return new Request(`https://fixture.test/api?company=${slug}`,{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}};
}
test('store DTO strips provider costs; every company-owned read scoped on server',async()=>{const f=fixture();const response=await f.store.GET(f.request());assert.equal(response.status,200);const value=await response.json();assert.equal(value.billingEnabled,false);assert.equal(value.book.config.whatsappCostCents,undefined);assert.equal(value.canManagePrices,false);assert.equal(response.headers.get('cache-control'),'private, no-store');for(const table of ['saas_order_drafts','saas_payment_account_drafts','saas_whatsapp_connections'])assert.ok(f.calls.some(c=>c.table===table&&c.method==='eq'&&c.args[0]==='tenant_company_id'&&c.args[1]===id(2)));});
test('composite RPC accepts record/one-row array, rejects missing or ambiguous results',()=>{assert.equal(rpc.rpcRow({id:'a'}).id,'a');assert.equal(rpc.rpcRow([{id:'a'}]).id,'a');for(const value of [null,{},[],[{id:'a'},{id:'b'}]])assert.throws(()=>rpc.rpcRow(value),/UNCERTAIN/);});
test('quote ignores forged total/exemption; draft tenant/actor cannot be body-selected',async()=>{const f=fixture();const response=await f.store.POST(f.request({action:'SAVE_DRAFT',pricebookId:id(8),requestId:id(7),studentCount:51,addons:['WHATSAPP'],exempt:true,monthlyCents:0,tenant_company_id:id(1),created_by:id(3)}));assert.equal(response.status,200);const value=await response.json();assert.equal(value.draft.quote.monthlyCents,29900);assert.equal(value.draft.quote.exempt,false);assert.equal(value.draft.quote.canCharge,false);assert.equal(f.writes[0].body.p_company,id(2));assert.equal(f.writes[0].body.p_actor,id(4));});
test('clients cannot alter platform prices/activate checkout; unauth/cross tenant denied',async()=>{const f=fixture();assert.equal((await f.store.POST(f.request({action:'SAVE_PRICEBOOK',config:rules.emptyPricebook()}))).status,403);assert.equal((await f.store.POST(f.request({action:'ACTIVATE'}))).status,409);assert.equal((await f.store.GET(f.request(null,'school','bad'))).status,401);assert.equal((await f.store.GET(f.request(null,'other'))).status,403);assert.equal(f.writes.length,0);});
test('plan stores preference only; scopes student/invoice reads; excludes card/provider identifiers',async()=>{const f=fixture();const response=await f.plan.GET(f.request());const value=await response.json();assert.equal(value.preview.monthlyCents,29900);assert.equal(value.billingEnabled,false);assert.equal(value.card,null);for(const table of ['saas_billing_preferences','xpace_people','saas_billing_invoices'])assert.ok(f.calls.some(c=>c.table===table&&c.method==='eq'&&c.args[1]===id(2)));assert.equal((await f.plan.POST(f.request({paymentMethod:'CREDIT_CARD',addons:['WHATSAPP']}))).status,200);assert.equal(f.writes[0].body.tenant_company_id,id(2));assert.equal(f.writes[0].body.updated_by,id(4));assert.equal(f.writes[0].body.card_number,undefined);assert.equal((await f.plan.POST(f.request({paymentMethod:'CREDIT_CARD',addons:[],cvv:'123'}))).status,400);});
test('non-manager cannot read or alter billing; owner company remains zero',async()=>{const f=fixture('company_staff');assert.equal((await f.plan.GET(f.request())).status,403);assert.equal((await f.plan.POST(f.request({paymentMethod:'PIX',addons:[]}))).status,403);assert.equal(f.writes.length,0);const owner=fixture('platform_owner',id(1));assert.equal((await(await owner.plan.GET(owner.request())).json()).preview.monthlyCents,0);});
test('actual company access helper checks server session, active profile and membership',async()=>{
 let profile={id:id(4),active:true,platform_role:'company_manager'},membership=null,user={id:id(4),user_metadata:{platform_role:'platform_owner'}};
 const admin={from(table){const b={};for(const method of ['select','eq','single','maybeSingle'])b[method]=()=>b;b.then=ok=>Promise.resolve({data:table==='companies'?{id:id(2),name:'school',slug:'school'}:table==='profiles'?profile:membership}).then(ok);return b;}};
 const mod=load('lib/server/company-access.ts',{'@/lib/server/supabase-admin':{createSupabaseAdmin:()=>admin,createSupabaseAuth:()=>({auth:{getUser:async()=>({data:{user}})}})}});
 const req=new Request('https://fixture.test',{headers:{authorization:'Bearer fixture'}});
 await assert.rejects(mod.requireCompanyAccess(req,'school'),e=>e.status===403);membership={company_id:id(2)};await mod.requireCompanyAccess(req,'school');profile={...profile,active:false};await assert.rejects(mod.requireCompanyAccess(req,'school'),e=>e.status===403);await assert.rejects(mod.requireCompanyAccess(new Request('https://fixture.test'),'school'),e=>e.status===401);
});
