const{PGlite}=require('@electric-sql/pglite');const assert=require('node:assert/strict'),fs=require('node:fs');const db=new PGlite();const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
(async()=>{try{
 await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
 create table companies(id uuid primary key);create table profiles(id uuid primary key,active boolean default true,platform_role text);create table company_members(profile_id uuid,company_id uuid,active boolean default true);
 create table xpace_instructors(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,full_name text,active boolean default true);
 create table xpace_rooms(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,name text,active boolean default true);
 create table xpace_class_groups(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,name text,modality text,active boolean default true,created_by uuid,updated_by uuid,unique(tenant_company_id,name));
 create table xpace_class_schedules(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,class_group_id uuid references xpace_class_groups(id),weekday int,starts_at time,ends_at time,room_id uuid,room_name text,instructor_id uuid,active boolean default true,created_by uuid);
 create table xpace_room_rentals(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,room_name text,renter_name text,starts_at timestamptz,ends_at timestamptz,amount_cents int,status text default 'RESERVADA',note text,created_by uuid,updated_at timestamptz default now());`);
 await db.exec(fs.readFileSync('supabase/migrations/20260914172043_xpace_rooms_and_schedule_conflicts.sql','utf8').split('create or replace function private.enforce_xpace_schedule_conflicts()')[1].split('alter table public.xpace_rooms enable')[0].replace(/^/,'create or replace function private.enforce_xpace_schedule_conflicts()'));
 await db.exec(fs.readFileSync('supabase/migrations/20261002165924_xpace_teaching_and_room_reservations.sql','utf8'));

 await db.exec(fs.readFileSync('supabase/migrations/20261002185328_xpace_independent_teacher_rosters.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261002194108_xpace_save_assigned_teacher_roster.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261002214429_xpace_roster_grade_snapshot.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20261002220527_xpace_teacher_month_attendance.sql','utf8'));

 await db.exec("alter table companies add column slug text;");
 const c=id(1),other=id(2),actor=id(3),teacher=id(4),room=id(5),prof=id(6),sub=id(7),room2=id(8);
 await db.query("insert into companies(id,slug) values($1,'xpace'),($2,'other')",[c,other]);await db.query("insert into profiles(id,platform_role) values($1,'platform_owner'),($2,'company_teacher')",[actor,teacher]);
 await db.query("insert into xpace_instructors(id,tenant_company_id,full_name,lesson_rate_cents) values($1,$2,'Ana',5000),($3,$2,'Beatriz',4000)",[prof,c,sub]);
 await db.query("insert into xpace_rooms(id,tenant_company_id,name) values($1,$2,'Sala 1'),($3,$2,'Sala 2')",[room,c,room2]);await db.query('insert into xpace_teacher_access values($1,$2,$3,true)',[teacher,c,prof]);
 const now=(await db.query("select (now() at time zone 'America/Sao_Paulo')::date::text as today,date_trunc('month',now() at time zone 'America/Sao_Paulo')::date::text as month")).rows[0];
 const create=(title='Teens',month='2026-09-01',person=null,r=room)=>db.query("select xpace_create_teacher_roster($1,$2,$3::date,$4,$5,$6,array[1,3],'19:00','19:45') id",[c,actor,month,title,person,r]);
 const roster=(await create()).rows[0].id;
 assert.equal((await db.query('select count(*)::int n from xpace_class_groups')).rows[0].n,0);
 assert.equal((await db.query('select count(*)::int n from xpace_class_schedules')).rows[0].n,0);
 const lessons=(await db.query('select * from xpace_teaching_lessons where roster_id=$1 order by scheduled_on',[roster])).rows;
 assert.deepEqual(lessons.map(l=>l.scheduled_on.toISOString().slice(0,10)),['2026-09-02','2026-09-07','2026-09-09','2026-09-14','2026-09-16','2026-09-21','2026-09-23','2026-09-28','2026-09-30']);
 assert.ok(lessons.every(l=>l.instructor_id===null&&l.schedule_id===null));
 await assert.rejects(()=>create(),/duplicate key/);
 const bulkDays=['2027-10-04','2027-10-06','2027-10-11','2027-10-13','2027-10-18','2027-10-20','2027-10-25','2027-10-27'];
 const assignments=bulkDays.map((day,i)=>({day,instructorId:i%2?sub:prof}));
 const bulk=(title,entries=assignments,r=room)=>db.query("select xpace_create_assigned_teacher_roster($1,$2,'2027-10-01',$3,$4,array[1,3],'19:00','20:00',$5::jsonb) id",[c,actor,title,r,JSON.stringify(entries)]);
 const saved=(await bulk('Teens completo')).rows[0].id;
 const savedRows=(await db.query('select * from xpace_teaching_lessons where roster_id=$1 order by scheduled_on',[saved])).rows;
 assert.deepEqual(savedRows.map(l=>l.instructor_id),assignments.map(a=>a.instructorId));assert.ok(savedRows.every(l=>l.status==='PREVISTA'&&l.schedule_id===null&&l.room_id===room));
 const snapshot=await db.query('select count(*)::int n from xpace_teaching_rosters');
 await assert.rejects(()=>bulk('Falha no último professor',assignments.map((a,i)=>({...a,instructorId:i===7?id(999):null}))),/INSTRUCTOR_INVALID/);
 assert.deepEqual((await db.query('select count(*)::int n from xpace_teaching_rosters')).rows,snapshot.rows);
 await assert.rejects(()=>bulk('Conflito de professor',assignments),/TEACHER_ROSTER_CONFLICT/);
 await assert.rejects(()=>bulk('Falta uma data',assignments.slice(1)),/ROSTER_ASSIGNMENTS_INVALID/);
 await assert.rejects(()=>bulk('Data duplicada',assignments.map(a=>({...a,day:bulkDays[0]}))),/ROSTER_ASSIGNMENTS_INVALID/);
 await assert.rejects(()=>bulk('Outro mês',assignments.map(a=>({...a,day:a.day.replace('10-','11-')}))),/ROSTER_ASSIGNMENTS_INVALID/);
 await db.query("insert into xpace_instructors(id,tenant_company_id,full_name,lesson_rate_cents) values($1,$2,'Outro tenant',5000)",[id(998),other]);
 await assert.rejects(()=>bulk('Outro tenant',assignments.map(a=>({...a,instructorId:id(998)}))),/INSTRUCTOR_INVALID/);
 assert.deepEqual((await db.query('select count(*)::int n from xpace_teaching_rosters')).rows,snapshot.rows);
 await db.query('update xpace_instructors set active=false where id=$1',[prof]);
 await assert.rejects(()=>bulk('Professor desativado',assignments.map((a,i)=>({...a,instructorId:i===7?prof:null}))),/INSTRUCTOR_INVALID/);
 await db.query('update xpace_instructors set active=true where id=$1',[prof]);
 await db.query("update xpace_teaching_months set reviewed_at=now() where tenant_company_id=$1 and month='2027-10-01'",[c]);
 await assert.rejects(()=>bulk('Mês fechado',assignments.map(a=>({...a,instructorId:null}))),/MONTH_CLOSED/);
 await db.query("update xpace_teaching_months set reviewed_at=null where tenant_company_id=$1 and month='2027-10-01'",[c]);
 assert.deepEqual((await db.query('select count(*)::int n from xpace_teaching_rosters')).rows,snapshot.rows);
 assert.equal((await db.query("select has_function_privilege('authenticated','xpace_create_assigned_teacher_roster(uuid,uuid,date,text,uuid,integer[],time,time,jsonb)','execute') f")).rows[0].f,false);
 const gradeDetails={name:'Street Dance',modality:'Street Dance',level:'INICIANTE',ageGroups:['TEENS'],roomName:'Sala 1',weekdays:[1,3],startsAt:'19:00',endsAt:'20:00'};
 const fullGrade=(key,details=gradeDetails,entries=assignments.map(a=>({...a,instructorId:null})),who=actor)=>db.query("select xpace_create_grade_teacher_roster($1,$2,'2027-10-01','Street Dance',$3,array[1,3],'19:00','20:00',$4::jsonb,$5::jsonb,$6) id",[c,who,room,JSON.stringify(entries),JSON.stringify(details),key]);
 const fullId=(await fullGrade('grade-teens')).rows[0].id;const adultId=(await fullGrade('grade-adulto',{...gradeDetails,ageGroups:['ADULTO']})).rows[0].id;
 assert.notEqual(fullId,adultId);assert.equal((await db.query('select grade_details from xpace_teaching_lessons where roster_id=$1',[fullId])).rows[0].grade_details.level,'INICIANTE');
 const beforeGradeFailure=(await db.query('select count(*)::int n from xpace_teaching_rosters')).rows[0].n;
 await assert.rejects(()=>fullGrade('grade-teens'),/duplicate key/);await assert.rejects(()=>fullGrade('grade-failure',gradeDetails,assignments.map((a,i)=>({...a,instructorId:i===7?id(999):null}))),/INSTRUCTOR_INVALID/);
 assert.equal((await db.query('select count(*)::int n from xpace_teaching_rosters')).rows[0].n,beforeGradeFailure);
 await assert.rejects(()=>fullGrade('grade-forbidden',gradeDetails,undefined,teacher),/TEACHER_FORBIDDEN/);
 assert.equal((await db.query("select has_function_privilege('authenticated','xpace_create_grade_teacher_roster(uuid,uuid,date,text,uuid,integer[],time,time,jsonb,jsonb,text)','execute') f")).rows[0].f,false);
 const lesson=lessons[0];const update=(person=prof,status='PREVISTA',teacherId=null,qr=null,r=room,start='19:00',end='19:45',company=c)=>db.query('select xpace_update_roster_lesson($1,$2,$3,$4,$5,$6,$7::time,$8::time,null,false,\'\',$9,$10)',[company,teacherId?teacher:actor,lesson.id,status,person,r,start,end,teacherId,qr]);
 await update(prof,'REALIZADA');assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,5000);
 await db.query('update xpace_instructors set lesson_rate_cents=6000 where id=$1',[prof]);await update(prof,'REALIZADA');assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,5000);
 await update(sub,'REALIZADA');assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,4000);
 await update(sub,'FALTOU');const absent=(await db.query('select status,rate_cents,confirmed_at,confirmed_by,confirmation_source from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0];assert.equal(absent.status,'FALTOU');assert.equal(absent.rate_cents,null);assert.equal(absent.confirmed_at,null);assert.equal(absent.confirmed_by,null);assert.equal(absent.confirmation_source,null);
 assert.equal((await db.query("select coalesce(sum(rate_cents) filter(where status='REALIZADA'),0)::int total from xpace_teaching_lessons where roster_id=$1",[roster])).rows[0].total,0);
 await db.query("update profiles set platform_role='company_manager' where id=$1",[actor]);await assert.rejects(()=>update(sub,'REALIZADA'),/ADMIN_REQUIRED/);await db.query("update profiles set platform_role='platform_owner' where id=$1",[actor]);
 await update(sub,'REALIZADA');assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,4000);
 await update(null);assert.equal((await db.query('select instructor_id from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].instructor_id,null);
 await assert.rejects(()=>update(null,'REALIZADA'),/LESSON_INVALID/);
 await update(prof);await assert.rejects(()=>update(prof,'REALIZADA',sub),/TEACHER_FORBIDDEN/);
 await assert.rejects(()=>update(prof,'REALIZADA',prof),/ATTENDANCE_WINDOW_CLOSED/);
 await db.query("update xpace_teaching_lessons set scheduled_on=$2::date, starts_at=(now() at time zone 'America/Sao_Paulo')::time,ends_at='23:59:59' where id=$1",[lesson.id,now.today]);
 await update(prof,'FALTOU');await assert.rejects(()=>update(prof,'REALIZADA',prof),/ATTENDANCE_WINDOW_CLOSED/);await assert.rejects(()=>update(prof,'FALTOU',prof),/TEACHER_FORBIDDEN/);await update(prof,'PREVISTA');await db.query("update xpace_teaching_lessons set starts_at=(now() at time zone 'America/Sao_Paulo')::time,ends_at='23:59:59' where id=$1",[lesson.id]);
 const token=(await db.query('select attendance_token from xpace_rooms where id=$1',[room])).rows[0].attendance_token;
 await assert.rejects(()=>update(prof,'REALIZADA',prof,id(999)),/ROOM_QR_INVALID/);
 await update(prof,'REALIZADA',prof,token);assert.equal((await db.query('select rate_cents,confirmation_source from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,6000);
 // Inclusive window boundaries use one transaction so PostgreSQL's now() is stable.
 await db.query("update xpace_teaching_lessons set status='PREVISTA' where id=$1",[lesson.id]);
 await db.query('begin');
 await db.query("update xpace_teaching_lessons set starts_at=((now() at time zone 'America/Sao_Paulo')-interval '15 minutes')::time where id=$1",[lesson.id]);
 await update(prof,'REALIZADA',prof,token);await db.query('commit');
 await db.query("update xpace_teaching_lessons set status='PREVISTA' where id=$1",[lesson.id]);await db.query('begin');
 await db.query("update xpace_teaching_lessons set starts_at=((now() at time zone 'America/Sao_Paulo')+interval '15 minutes')::time where id=$1",[lesson.id]);
 await update(prof,'REALIZADA',prof,token);await db.query('commit');
 const audit=(await db.query('select count(*)::int n from xpace_teaching_audit')).rows[0].n;await update(prof,'REALIZADA',prof,token);assert.equal((await db.query('select count(*)::int n from xpace_teaching_audit')).rows[0].n,audit);
 await db.query("update xpace_teaching_lessons set status='PREVISTA',starts_at=((now() at time zone 'America/Sao_Paulo')-interval '16 minutes')::time,ends_at='23:59:59' where id=$1",[lesson.id]);
 await assert.rejects(()=>update(prof,'REALIZADA',prof,token),/ATTENDANCE_WINDOW_CLOSED/);
 await db.query("update xpace_teaching_lessons set starts_at=((now() at time zone 'America/Sao_Paulo')+interval '16 minutes')::time where id=$1",[lesson.id]);
 await assert.rejects(()=>update(prof,'REALIZADA',prof,token),/ATTENDANCE_WINDOW_CLOSED/);
 await db.query("update xpace_teaching_lessons set starts_at=((now() at time zone 'America/Sao_Paulo')-interval '14 minutes')::time where id=$1",[lesson.id]);await update(prof,'REALIZADA',prof,token);
 await db.query('select xpace_review_teaching_month($1,$2,$3::date,false,\'\')',[c,actor,'2026-09-01']);
 // The changed date is in current month; closing that month also blocks corrections.
 await db.query('insert into xpace_teaching_months(tenant_company_id,month,reviewed_at) values($1,$2::date,now()) on conflict(tenant_company_id,month) do update set reviewed_at=now()',[c,now.month]);
 await assert.rejects(()=>update(),/MONTH_CLOSED/);await assert.rejects(()=>update(prof,'PREVISTA',null,null,room,'19:00','19:45',other),/LESSON_NOT_FOUND/);
 // Teacher staffing does not occupy rooms. Only academic schedules and actual rentals do.
 await db.query("select xpace_review_teaching_month($1,$2,$3::date,true,'Teste de reabertura')",[c,actor,now.month]);
 const future=(await db.query("select ((now() at time zone 'America/Sao_Paulo')::date+((8-extract(dow from now() at time zone 'America/Sao_Paulo')::int)%7)+7)::text as day")).rows[0].day;
 const month=future.slice(0,7)+'-01';
 await create('Livre para aluguel',month,null,room2);
 await db.query("select xpace_reserve_teacher_room($1,$2,$3,$4,($5::date+'19:00'::time) at time zone 'America/Sao_Paulo',($5::date+'19:30'::time) at time zone 'America/Sao_Paulo',$6)",[c,teacher,prof,room2,future,id(40)]);
 const rental=(await db.query('select * from xpace_room_rentals')).rows[0];assert.equal(rental.amount_cents,1750);
 await db.query("insert into xpace_room_rentals(tenant_company_id,room_name,starts_at,ends_at,status) values($1,'Sala 1',now(),now()+interval '1 hour','CANCELADA'),($2,'Outra',now(),now()+interval '1 hour','CANCELADA')",[c,other]);
 await db.exec(fs.readFileSync('supabase/migrations/20261002185339_xpace_cancelled_reservations_no_charge.sql','utf8'));
 assert.equal((await db.query("select cancellation_charge_cents from xpace_room_rentals where tenant_company_id=$1 and room_name='Sala 1'",[c])).rows[0].cancellation_charge_cents,0);
 assert.equal((await db.query("select cancellation_charge_cents from xpace_room_rentals where tenant_company_id=$1",[other])).rows[0].cancellation_charge_cents,null);
 await db.query("select xpace_cancel_teacher_reservation($1,$2,$3,$4,null,false,'Não vou usar')",[c,teacher,rental.id,prof]);
 const cancelled=(await db.query('select status,cancellation_charge_cents from xpace_room_rentals where id=$1',[rental.id])).rows[0];assert.deepEqual(cancelled,{status:'CANCELADA',cancellation_charge_cents:0});
 await db.query("insert into xpace_class_groups(id,tenant_company_id,name,modality) values($1,$2,'Grade acadêmica','Dança')",[id(50),c]);
 await db.query("insert into xpace_class_schedules(tenant_company_id,class_group_id,weekday,starts_at,ends_at,room_id,room_name,instructor_id) values($1,$2,extract(dow from $3::date),'19:00','20:00',$4,'Sala 2',$5)",[c,id(50),future,room2,prof]);
 await assert.rejects(()=>db.query("select xpace_reserve_teacher_room($1,$2,$3,$4,($5::date+'19:00'::time) at time zone 'America/Sao_Paulo',($5::date+'19:30'::time) at time zone 'America/Sao_Paulo',$6)",[c,teacher,prof,room2,future,id(41)]),/CONFLITO/);
 const history=(await db.query("insert into xpace_room_rentals(tenant_company_id,room_name,starts_at,ends_at,created_by) values($1,'Histórico 04h',($2::date+'04:00'::time) at time zone 'America/Sao_Paulo',($2::date+'05:00'::time) at time zone 'America/Sao_Paulo',$3) returning id",[c,future,actor])).rows[0].id;
 await db.exec(fs.readFileSync('supabase/migrations/20261002200053_xpace_room_reservation_hours.sql','utf8'));
 await db.exec("set timezone='Asia/Tokyo'");
 const hoursDay=(await db.query("select ($1::date+1)::text as day",[future])).rows[0].day;
 const reserveHours=(start,end,request)=>db.query('select xpace_reserve_teacher_room($1,$2,$3,$4,$5::timestamptz,$6::timestamptz,$7)',[c,teacher,prof,room,hoursDay+'T'+start+'-03:00',hoursDay+'T'+end+'-03:00',id(request)]);
 for(const [start,end] of[['04:00:00','05:00:00'],['07:59:00','08:30:00'],['21:30:00','22:01:00']])await assert.rejects(()=>reserveHours(start,end,70),/RESERVATION_HOURS/);
 await reserveHours('08:00:00','08:30:00',71);await reserveHours('21:30:00','22:00:00',72);await reserveHours('21:30:00','22:00:00',72);
 const fullDay=(await db.query("select ($1::date+2)::text as day",[future])).rows[0].day;
 await db.query("select xpace_reserve_teacher_room($1,$2,$3,$4,($5::date+'08:00'::time) at time zone 'America/Sao_Paulo',($5::date+'22:00'::time) at time zone 'America/Sao_Paulo',$6)",[c,teacher,prof,room,fullDay,id(73)]);
 assert.equal((await db.query('select amount_cents from xpace_room_rentals where request_id=$1',[id(73)])).rows[0].amount_cents,49000);
 await assert.rejects(()=>db.query("insert into xpace_room_rentals(tenant_company_id,room_name,starts_at,ends_at) values($1,'Locação antiga',($2::date+'04:00'::time) at time zone 'America/Sao_Paulo',($2::date+'05:00'::time) at time zone 'America/Sao_Paulo')",[c,hoursDay]),/RESERVATION_HOURS/);
 await db.query("insert into xpace_room_rentals(tenant_company_id,room_name,starts_at,ends_at) values($1,'Outra empresa',($2::date+'04:00'::time) at time zone 'America/Sao_Paulo',($2::date+'05:00'::time) at time zone 'America/Sao_Paulo')",[other,hoursDay]);
 assert.equal((await db.query('select status from xpace_room_rentals where id=$1',[history])).rows[0].status,'RESERVADA');
 await db.query("select xpace_cancel_teacher_reservation($1,$2,$3,null,null,false,'Cancelamento de histórico')",[c,actor,history]);
 assert.equal((await db.query('select status from xpace_room_rentals where id=$1',[history])).rows[0].status,'CANCELADA');
 const grants=(await db.query("select has_table_privilege('authenticated','xpace_teaching_rosters','select') r,has_function_privilege('authenticated','xpace_create_teacher_roster(uuid,uuid,date,text,uuid,uuid,integer[],time,time)','execute') f")).rows[0];assert.deepEqual(grants,{r:false,f:false});
 console.log('Teacher roster DB: PASS (independent September dates, unassigned slots, per-date assignment/rates, QR 15/15/day/owner/room/idempotency, review locks, rentals independent but academic collisions blocked, cancellation waived and RLS).');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
