const{PGlite}=require('@electric-sql/pglite');const assert=require('node:assert/strict'),fs=require('node:fs');const db=new PGlite();const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
(async()=>{try{
 await db.exec(`create schema private;create role anon;create role authenticated;create role service_role;
 create table companies(id uuid primary key);create table profiles(id uuid primary key,active boolean default true,platform_role text);create table company_members(profile_id uuid,company_id uuid,active boolean default true);
 create table xpace_instructors(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,full_name text,active boolean default true);
 create table xpace_rooms(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,name text,active boolean default true);
 create table xpace_class_groups(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,name text,modality text,active boolean default true,created_by uuid,updated_by uuid,unique(tenant_company_id,name));
 create table xpace_class_schedules(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,class_group_id uuid references xpace_class_groups(id),weekday int,starts_at time,ends_at time,room_id uuid,room_name text,instructor_id uuid,active boolean default true,created_by uuid);
 create table xpace_room_rentals(id uuid primary key default gen_random_uuid(),tenant_company_id uuid,room_name text,renter_name text,starts_at timestamptz,ends_at timestamptz,amount_cents int,status text default 'RESERVADA',note text,created_by uuid,updated_at timestamptz default now());`);
 await db.exec(fs.readFileSync('supabase/migrations/20260914172043_xpace_rooms_and_schedule_conflicts.sql','utf8').split('create or replace function private.enforce_xpace_schedule_conflicts()')[1].split('alter table public.xpace_rooms enable')[0].replace(/^/,'create or replace function private.enforce_xpace_schedule_conflicts()'));
 await db.exec(fs.readFileSync('supabase/migrations/20261002141514_xpace_teaching_and_room_reservations.sql','utf8'));
 const c=id(1),other=id(2),actor=id(3),teacher=id(4),room=id(5),prof=id(6),sub=id(7);
 await db.query('insert into companies values($1),($2)',[c,other]);await db.query("insert into profiles(id,platform_role) values($1,'platform_owner'),($2,'company_teacher')",[actor,teacher]);
 await db.query("insert into xpace_instructors(id,tenant_company_id,full_name,lesson_rate_cents) values($1,$2,'Alceu',5000),($3,$2,'Substituto',4000)",[prof,c,sub]);
 await db.query("insert into xpace_rooms(id,tenant_company_id,name) values($1,$2,'Sala 1')",[room,c]);await db.query('insert into xpace_teacher_access values($1,$2,$3,true)',[teacher,c,prof]);
 const clock=(await db.query("select (now() at time zone 'America/Sao_Paulo')::date::text as today, date_trunc('month',now() at time zone 'America/Sao_Paulo')::date::text as month")).rows[0];
 const tomorrow=new Date(clock.today+'T12:00:00Z');tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const on=tomorrow.toISOString().slice(0,10),weekday=tomorrow.getUTCDay(),month=on.slice(0,7)+'-01';
 await db.query("select xpace_create_teaching_grade($1,$2,'Teens',$3,$4,$5::int[],'19:00','19:45',$6::date)",[c,actor,prof,room,[weekday],on]);
 await db.query('select xpace_prepare_teaching_month($1,$2::date)',[c,month]);await db.query('select xpace_prepare_teaching_month($1,$2::date)',[c,month]);
 const lessons=(await db.query('select * from xpace_teaching_lessons where tenant_company_id=$1 order by scheduled_on',[c])).rows;assert.ok(lessons.length>=1);assert.equal(new Set(lessons.map(l=>l.scheduled_on)).size,lessons.length);
 const lesson=lessons[0];const update=(status='REALIZADA',instructor=prof,rate=null,override=false,t=null,who=actor,qr=null)=>db.query('select xpace_change_teaching_lesson($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[c,who,lesson.id,status,instructor,rate,override,'',t,qr]);
 await update();assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,5000);
 await db.query('update xpace_instructors set lesson_rate_cents=6000 where id=$1',[prof]);await update();assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,5000);
 await update('REALIZADA',sub);assert.equal((await db.query('select rate_cents from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0].rate_cents,4000);
 await assert.rejects(()=>update('REALIZADA',prof,null,false,prof,teacher),/TEACHER_FORBIDDEN/);
 await db.query('select xpace_review_teaching_month($1,$2,$3::date,false,\'\')',[c,actor,month]);await assert.rejects(()=>update(),/MONTH_CLOSED/);
 await assert.rejects(()=>db.query('select xpace_review_teaching_month($1,$2,$3::date,true,\'\')',[c,actor,month]),/REASON_REQUIRED/);
 await db.query('select xpace_review_teaching_month($1,$2,$3::date,true,\'Correção\')',[c,actor,month]);await update('REALIZADA',prof,0,true);
 await update('PREVISTA',prof,null,false);
 await assert.rejects(()=>update('REALIZADA',prof,null,false,prof,teacher),/ATTENDANCE_WINDOW_CLOSED/);
 await db.query("update xpace_teaching_lessons set scheduled_on=$2::date,starts_at='00:00',ends_at='23:59' where id=$1",[lesson.id,clock.today]);
 await assert.rejects(()=>update('REALIZADA',prof,null,false,prof,teacher,id(999)),/ROOM_QR_INVALID/);
 const token=(await db.query('select attendance_token from xpace_rooms where id=$1',[room])).rows[0].attendance_token;
 await update('REALIZADA',prof,null,false,prof,teacher,token);
 const afterQr=(await db.query('select rate_cents,confirmation_source from xpace_teaching_lessons where id=$1',[lesson.id])).rows[0];assert.equal(afterQr.rate_cents,6000);assert.equal(afterQr.confirmation_source,'QR');
 const auditCount=(await db.query('select count(*)::int n from xpace_teaching_audit')).rows[0].n;await update('REALIZADA',prof,null,false,prof,teacher,token);assert.equal((await db.query('select count(*)::int n from xpace_teaching_audit')).rows[0].n,auditCount);
 await db.query("update xpace_teaching_lessons set scheduled_on=$2::date,starts_at='19:00',ends_at='19:45' where id=$1",[lesson.id,on]);
 const reserve=(start,end,request=id(30),company=c)=>db.query('select xpace_reserve_teacher_room($1,$2,$3,$4,$5::timestamptz,$6::timestamptz,$7)',[company,teacher,prof,room,start,end,request]);
 await assert.rejects(()=>reserve(on+'T19:15:00-03:00',on+'T19:30:00-03:00'),/CONFLITO/);
 const start=on+'T18:00:00-03:00',end=on+'T18:30:00-03:00';await reserve(start,end);await reserve(start,end);
 const rental=(await db.query('select * from xpace_room_rentals')).rows[0];assert.equal(rental.amount_cents,1750);assert.equal(rental.hourly_rate_cents,3500);
 await db.query('update xpace_rooms set hourly_rate_cents=4000 where id=$1',[room]);assert.equal((await db.query('select amount_cents from xpace_room_rentals')).rows[0].amount_cents,1750);
 await assert.rejects(()=>reserve(start,end,id(31)),/CONFLITO/);await assert.rejects(()=>reserve(start,end,id(30),other),/REPLAY_MISMATCH/);
 await reserve(on+'T18:30:00-03:00',on+'T19:00:00-03:00',id(32));
 await assert.rejects(()=>db.query("select xpace_create_teaching_grade($1,$2,'Conflitante',$3,$4,$5::int[],'18:00','18:15',$6::date)",[c,actor,prof,room,[weekday],on]),/CONFLITO COM RESERVA/);
 await update('CANCELADA');await reserve(on+'T19:00:00-03:00',on+'T19:45:00-03:00',id(33));await assert.rejects(()=>update('PREVISTA'),/CONFLITO DE SALA/);
 await assert.rejects(()=>db.query("select xpace_cancel_teacher_reservation($1,$2,$3,$4,null,false,'Não vou usar')",[c,teacher,rental.id,sub]),/RESERVATION_NOT_FOUND/);
 await db.query("select xpace_cancel_teacher_reservation($1,$2,$3,$4,null,false,'Não vou usar')",[c,teacher,rental.id,prof]);assert.equal((await db.query('select cancellation_charge_cents from xpace_room_rentals where id=$1',[rental.id])).rows[0].cancellation_charge_cents,null);
 await db.query("select xpace_cancel_teacher_reservation($1,$2,$3,null,500,true,'Cobrança parcial')",[c,actor,rental.id]);assert.equal((await db.query('select cancellation_charge_cents from xpace_room_rentals where id=$1',[rental.id])).rows[0].cancellation_charge_cents,500);
 await assert.rejects(()=>db.query('insert into company_members values($1,$2,true)',[teacher,c]),/TEACHER_MEMBERSHIP_FORBIDDEN/);
 await assert.rejects(()=>reserve(on+'T21:00:00-03:00',on+'T21:30:00-03:00',id(88),other),/ROOM_INVALID/);
 const grants=(await db.query("select has_table_privilege('authenticated','xpace_teaching_lessons','select') can_read,has_function_privilege('authenticated','xpace_change_teaching_lesson(uuid,uuid,uuid,text,uuid,integer,boolean,text,uuid,uuid)','execute') can_change")).rows[0];assert.deepEqual(grants,{can_read:false,can_change:false});
 console.log('Teaching DB: PASS (recurrence deduplication, full 45-minute lesson rate, substitute snapshots, monthly review, teacher isolation, room/class conflicts, adjacent intervals, proportional rate and idempotency).');
}finally{await db.close();}})().catch(e=>{console.error(e.message||e);process.exitCode=1;});
