'use client';
import{useEffect,useState,type FormEvent}from'react';
import{X}from'lucide-react';
import{teachingApi}from'./TeachingWorkspace';
import'./teaching.css';
export default function InstructorAccessDialog({instructor,onClose}:{instructor:{id:string;fullName:string;email:string};onClose:()=>void}){
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[access,setAccess]=useState<{active:boolean;email:string}|null>(null),[email,setEmail]=useState(instructor.email),[password,setPassword]=useState(''),[active,setActive]=useState(true),[notice,setNotice]=useState('');
 useEffect(()=>{void teachingApi<{access:{active:boolean;email:string}|null}>('/api/xpace/professores/acesso?id='+instructor.id).then(p=>{setAccess(p.access);if(p.access){setEmail(p.access.email);setActive(p.access.active);}}).catch(e=>setNotice(e.message)).finally(()=>setLoading(false));},[instructor.id]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setNotice('');try{await teachingApi('/api/xpace/professores/acesso',{method:access?'PATCH':'POST',body:JSON.stringify({instructorId:instructor.id,email,password:password||undefined,active})});setPassword('');setAccess({active,email});setNotice('ACESSO SALVO. COMPARTILHE A SENHA POR UM CANAL PRIVADO.');}catch(e){setNotice(e instanceof Error?e.message:'ERRO AO SALVAR.');}finally{setBusy(false);}}
 return <div className="tw-workspace tw-modal" role="dialog" aria-modal="true" aria-labelledby="teacher-access-title"><form onSubmit={save}><header><h3 id="teacher-access-title">Acesso do professor</h3><button type="button" aria-label="Fechar" onClick={onClose} disabled={busy}><X size={18}/></button></header><p className="tw-small">{instructor.fullName} · Somente Grade de aulas, Ocupação e Reserva.</p>{notice?<p className="tw-notice" role="status">{notice}</p>:null}{loading?<p className="tw-small">Conferindo o acesso…</p>:<><label>E-MAIL DE LOGIN<input type="email" required value={email} disabled={Boolean(access)} onChange={e=>setEmail(e.target.value)}/></label><label>{access?'NOVA SENHA · OPCIONAL':'SENHA INICIAL'}<input type="password" autoComplete="new-password" minLength={10} maxLength={128} required={!access} value={password} onChange={e=>setPassword(e.target.value)}/><small>Mínimo de 10 caracteres.</small></label>{access?<label className="tw-checkbox"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Acesso ativo</label>:null}<p className="tw-small">Aplicativo: <a href="/xpace/professor" target="_blank" rel="noopener noreferrer">Abrir espaço do professor</a>. No celular, use “Adicionar à tela de início”.</p><footer><button type="button" className="tw-secondary" onClick={onClose} disabled={busy}>FECHAR</button><button className="tw-primary" disabled={busy}>{busy?'SALVANDO…':access?'SALVAR ACESSO':'CRIAR ACESSO'}</button></footer></>}</form></div>;
}
