"use client";

import { CalendarPlus, CheckCircle2, ClipboardCopy, MessageSquarePlus, Plus, RotateCcw, Save, UserRoundPlus, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";

import { supabase } from "@/lib/supabase";

const stages = ["NOVO", "ATENDIMENTO", "AULA_EXPERIMENTAL", "NEGOCIACAO", "GANHO", "PERDIDO"] as const;
const stageLabel: Record<string, string> = { NOVO: "NOVOS", ATENDIMENTO: "ATENDIMENTO", AULA_EXPERIMENTAL: "EXPERIMENTAL", NEGOCIACAO: "NEGOCIAÇÃO", GANHO: "GANHOS", PERDIDO: "PERDIDOS" };
type Lead = { id: string; lead_number: number; full_name: string; mobile: string | null; email: string | null; pipeline_stage: string; source_id: string | null; source_note: string | null; assigned_to: string | null; loss_reason_id: string | null; loss_note: string | null; created_at: string; updated_at: string };
type Appointment = { id: string; lead_id: string; class_group_id: string | null; class_schedule_id: string | null; scheduled_on: string; starts_at: string | null; ends_at: string | null; booking_kind: string; confirmation_status: string; attendance_status: string; enrollment_outcome: string; assigned_to: string | null; modality_name_snapshot: string | null; instructor_name_snapshot: string | null; class_name_snapshot: string | null; note: string | null; survey_status: string; welcome_video_url: string | null; welcome_delivery_status: string; updated_at: string };
type Activity = { id: string; lead_id: string; appointment_id: string | null; activity_type: string; body: string | null; created_at: string };
type Group = { id: string; name: string; modality: string; instructorName: string; allowsLeads: boolean; schedules: Array<{ id: string; weekday: number; startsAt: string; endsAt: string; roomName: string }> };
type Workspace = { leads: Lead[]; appointments: Appointment[]; activities: Activity[]; sources: Array<{ id: string; name: string; active: boolean }>; lossReasons: Array<{ id: string; name: string; active: boolean }>; attendants: Array<{ id: string; full_name: string }>; groups: Group[] };
const blank: Workspace = { leads: [], appointments: [], activities: [], sources: [], lossReasons: [], attendants: [], groups: [] };

export default function LeadsWorkspace() {
  const [workspace, setWorkspace] = useState<Workspace>(blank);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState("");
  const [creating, setCreating] = useState(false);
  const [draft, setDraft] = useState({ fullName: "", mobile: "", email: "", sourceId: "" });

  useEffect(() => { void load(); }, []);
  const selected = workspace.leads.find((lead) => lead.id === selectedId) ?? null;
  const visible = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("pt-BR"); return normalized ? workspace.leads.filter((lead) => `${lead.full_name} ${lead.mobile ?? ""} ${lead.email ?? ""}`.toLocaleLowerCase("pt-BR").includes(normalized)) : workspace.leads; }, [workspace.leads, query]);
  const appointmentsByLead = useMemo(() => new Map(workspace.leads.map((lead) => [lead.id, workspace.appointments.filter((item) => item.lead_id === lead.id)])), [workspace]);
  const stats = useMemo(() => ({ active: workspace.leads.filter((lead) => !["GANHO", "PERDIDO"].includes(lead.pipeline_stage)).length, scheduled: workspace.appointments.filter((item) => item.attendance_status === "AGENDADO").length, attended: workspace.appointments.filter((item) => item.attendance_status === "COMPARECEU").length, won: workspace.leads.filter((lead) => lead.pipeline_stage === "GANHO").length }), [workspace]);

  async function request<T>(path: string, init?: RequestInit): Promise<T> {
    const { data } = await supabase.auth.getSession(); const token = data.session?.access_token;
    if (!token) throw new Error("SESSÃO NÃO ENCONTRADA.");
    const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...init?.headers } });
    const payload = await response.json().catch(() => ({})) as { success?: boolean; message?: string } & T;
    if (!response.ok || !payload.success) throw new Error(payload.message || "NÃO FOI POSSÍVEL CONCLUIR A OPERAÇÃO.");
    return payload;
  }
  async function load() { setLoading(true); try { setWorkspace(await request<Workspace>("/api/xpace/leads")); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL CARREGAR O CRM."); } finally { setLoading(false); } }
  async function action(payload: unknown, success?: string) { try { setNotice(""); await request("/api/xpace/leads", { method: "POST", body: JSON.stringify(payload) }); if (success) setNotice(success); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL ATUALIZAR O CRM."); } }
  async function createLead(event: FormEvent) { event.preventDefault(); await action({ action: "CREATE_LEAD", lead: { ...draft, pipelineStage: "NOVO" } }, "LEAD CADASTRADO."); setDraft({ fullName: "", mobile: "", email: "", sourceId: "" }); setCreating(false); }
  async function copyPublicLink() { try { await navigator.clipboard.writeText(`${window.location.origin}/aula-experimental`); setNotice("LINK DE AGENDAMENTO COPIADO."); } catch { setNotice("LINK: /aula-experimental"); } }

  return <section className="xd-leads">
    <header className="xd-leads-heading"><div><span>RELACIONAMENTO E CONVERSÃO</span><h1>CRM DE LEADS.</h1><p>Controle cada experimental sem misturar interessados com alunos ou vendas financeiras.</p></div><div className="xd-leads-heading-actions"><button type="button" className="xd-secondary" onClick={() => { void copyPublicLink(); }}><ClipboardCopy size={15} /> LINK DE AGENDAMENTO</button><button type="button" className="xd-primary" onClick={() => setCreating(true)}><UserRoundPlus size={16} /> NOVO LEAD</button></div></header>
    <section className="xd-lead-stats"><article><small>EM FUNIL</small><strong>{stats.active}</strong></article><article><small>AGENDADOS</small><strong>{stats.scheduled}</strong></article><article><small>COMPARECERAM</small><strong>{stats.attended}</strong></article><article><small>GANHOS</small><strong>{stats.won}</strong></article></section>
    <section className="xd-leads-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="BUSCAR POR NOME, TELEFONE OU E-MAIL" /><button type="button" className="xd-secondary" onClick={() => { void load(); }}><RotateCcw size={15} /> ATUALIZAR</button></section>
    {notice ? <p className="xd-feedback">{notice}</p> : null}
    {loading ? <p className="xd-leads-empty">CARREGANDO LEADS...</p> : <section className="xd-leads-board" aria-label="Funil de leads">{stages.map((stage) => <article className="xd-lead-column" key={stage}><header><span>{stageLabel[stage]}</span><b>{visible.filter((lead) => lead.pipeline_stage === stage).length}</b></header><div>{visible.filter((lead) => lead.pipeline_stage === stage).map((lead) => <button type="button" className="xd-lead-card" key={lead.id} onClick={() => setSelectedId(lead.id)}><strong>{lead.full_name}</strong><small>{lead.mobile || lead.email || "SEM CONTATO"}</small><em>{appointmentSummary(appointmentsByLead.get(lead.id) ?? [])}</em></button>)}{!visible.some((lead) => lead.pipeline_stage === stage) ? <p>SEM LEADS</p> : null}</div></article>)}</section>}
    {creating ? <LeadCreateForm draft={draft} sources={workspace.sources} onChange={setDraft} onClose={() => setCreating(false)} onSubmit={createLead} /> : null}
    {selected ? <LeadDetail lead={selected} workspace={workspace} onClose={() => setSelectedId("")} onAction={action} /> : null}
  </section>;
}

function LeadCreateForm({ draft, sources, onChange, onClose, onSubmit }: { draft: { fullName: string; mobile: string; email: string; sourceId: string }; sources: Workspace["sources"]; onChange: (value: { fullName: string; mobile: string; email: string; sourceId: string }) => void; onClose: () => void; onSubmit: (event: FormEvent) => Promise<void> }) {
  return <div className="xd-contract-overlay"><form className="xd-settings-dialog xd-lead-create" onSubmit={(event) => { void onSubmit(event); }}><header><span><UserRoundPlus size={20} /></span><h2>NOVO LEAD</h2><button type="button" onClick={onClose} aria-label="Fechar">×</button></header><div><label>NOME COMPLETO<input value={draft.fullName} onChange={(event) => onChange({ ...draft, fullName: event.target.value })} required /></label><label>TELEFONE<input value={draft.mobile} onChange={(event) => onChange({ ...draft, mobile: event.target.value })} /></label><label>E-MAIL<input type="email" value={draft.email} onChange={(event) => onChange({ ...draft, email: event.target.value })} /></label><label>COMO CONHECEU<select value={draft.sourceId} onChange={(event) => onChange({ ...draft, sourceId: event.target.value })}><option value="">NÃO INFORMADO</option>{sources.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><footer><button type="button" className="xd-secondary" onClick={onClose}>CANCELAR</button><button className="xd-primary" type="submit"><Plus size={16} /> CADASTRAR</button></footer></form></div>;
}

function LeadDetail({ lead, workspace, onClose, onAction }: { lead: Lead; workspace: Workspace; onClose: () => void; onAction: (payload: unknown, success?: string) => Promise<void> }) {
  const [stage, setStage] = useState(lead.pipeline_stage); const [sourceId, setSourceId] = useState(lead.source_id ?? ""); const [assignedTo, setAssignedTo] = useState(lead.assigned_to ?? ""); const [lossReasonId, setLossReasonId] = useState(lead.loss_reason_id ?? ""); const [lossNote, setLossNote] = useState(lead.loss_note ?? ""); const [note, setNote] = useState(""); const [booking, setBooking] = useState({ classGroupId: "", classScheduleId: "", scheduledOn: "", bookingKind: "NOVO" });
  const appointments = workspace.appointments.filter((item) => item.lead_id === lead.id).sort((left, right) => right.scheduled_on.localeCompare(left.scheduled_on)); const activities = workspace.activities.filter((item) => item.lead_id === lead.id).slice(0, 16); const groups = workspace.groups.filter((item) => item.allowsLeads); const selectedGroup = groups.find((item) => item.id === booking.classGroupId);
  useEffect(() => { setStage(lead.pipeline_stage); setSourceId(lead.source_id ?? ""); setAssignedTo(lead.assigned_to ?? ""); setLossReasonId(lead.loss_reason_id ?? ""); setLossNote(lead.loss_note ?? ""); }, [lead]);
  return <div className="xd-contract-overlay"><section className="xd-lead-detail" role="dialog" aria-modal="true" aria-label={`Lead ${lead.full_name}`}><header><div><small>LEAD #{lead.lead_number}</small><h2>{lead.full_name}</h2><p>{lead.mobile || "SEM TELEFONE"}{lead.email ? ` · ${lead.email}` : ""}</p></div><button type="button" onClick={onClose} aria-label="Fechar"><X size={21} /></button></header><div className="xd-lead-detail-content"><section className="xd-lead-detail-section"><h3>FUNIL E RESPONSÁVEL</h3><div className="xd-lead-detail-fields"><label>ETAPA<select value={stage} onChange={(event) => setStage(event.target.value)}>{stages.map((item) => <option value={item} key={item}>{stageLabel[item]}</option>)}</select></label><label>ATENDENTE<select value={assignedTo} onChange={(event) => setAssignedTo(event.target.value)}><option value="">SEM RESPONSÁVEL</option>{workspace.attendants.map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>ORIGEM<select value={sourceId} onChange={(event) => setSourceId(event.target.value)}><option value="">NÃO INFORMADO</option>{workspace.sources.filter((item) => item.active || item.id === sourceId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{stage === "PERDIDO" ? <><label>MOTIVO<select value={lossReasonId} onChange={(event) => setLossReasonId(event.target.value)}><option value="">SELECIONE</option>{workspace.lossReasons.filter((item) => item.active || item.id === lossReasonId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="xd-lead-field-wide">OBSERVAÇÃO DA PERDA<input value={lossNote} onChange={(event) => setLossNote(event.target.value)} /></label></> : null}</div><button className="xd-primary" type="button" onClick={() => { void onAction({ action: "UPDATE_LEAD", lead: { id: lead.id, pipelineStage: stage, sourceId, assignedTo, lossReasonId, lossNote } }, "LEAD ATUALIZADO."); }}><Save size={15} /> SALVAR FUNIL</button></section>
    <section className="xd-lead-detail-section"><h3><CalendarPlus size={17} /> NOVA EXPERIMENTAL</h3><div className="xd-lead-detail-fields"><label>TURMA<select value={booking.classGroupId} onChange={(event) => setBooking({ ...booking, classGroupId: event.target.value, classScheduleId: "" })}><option value="">SELECIONE</option>{groups.map((group) => <option value={group.id} key={group.id}>{group.name} · {group.modality}</option>)}</select></label><label>HORÁRIO<select value={booking.classScheduleId} onChange={(event) => setBooking({ ...booking, classScheduleId: event.target.value })} disabled={!selectedGroup}><option value="">SELECIONE</option>{selectedGroup?.schedules.map((schedule) => <option value={schedule.id} key={schedule.id}>{weekday(schedule.weekday)} · {schedule.startsAt}–{schedule.endsAt}{schedule.roomName ? ` · ${schedule.roomName}` : ""}</option>)}</select></label><label>DATA<input type="date" value={booking.scheduledOn} onChange={(event) => setBooking({ ...booking, scheduledOn: event.target.value })} /></label><label>TIPO<select value={booking.bookingKind} onChange={(event) => setBooking({ ...booking, bookingKind: event.target.value })}><option value="NOVO">NOVA EXPERIMENTAL</option><option value="REAGENDAMENTO">REAGENDAMENTO</option><option value="RECUPERACAO">RECUPERAÇÃO</option></select></label></div><button className="xd-secondary" type="button" disabled={!booking.classScheduleId || !booking.scheduledOn} onClick={() => { void onAction({ action: "CREATE_APPOINTMENT", appointment: { ...booking, leadId: lead.id } }, "AULA EXPERIMENTAL AGENDADA."); }}><CalendarPlus size={15} /> AGENDAR</button><p className="xd-lead-policy">ATÉ DUAS EXPERIMENTAIS GRATUITAS. A TERCEIRA DEVE SER TRATADA COMO AULA COM TAXA.</p></section>
    <section className="xd-lead-detail-section"><h3>AGENDAMENTOS</h3>{appointments.length ? <div className="xd-lead-appointments">{appointments.map((appointment) => <AppointmentEditor key={appointment.id} appointment={appointment} onSave={(patch) => onAction({ action: "UPDATE_APPOINTMENT", appointment: { id: appointment.id, ...patch } }, "AGENDAMENTO ATUALIZADO.")} />)}</div> : <p className="xd-lead-empty">NENHUMA AULA EXPERIMENTAL CADASTRADA.</p>}</section>
    <section className="xd-lead-detail-section"><h3><MessageSquarePlus size={17} /> HISTÓRICO</h3><div className="xd-lead-note"><input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Registrar contato ou observação" /><button type="button" className="xd-secondary" disabled={!note.trim()} onClick={() => { void onAction({ action: "ADD_NOTE", lead: { id: lead.id }, note }, "OBSERVAÇÃO REGISTRADA."); setNote(""); }}>ADICIONAR</button></div><div className="xd-lead-timeline">{activities.map((activity) => <article key={activity.id}><time>{dateTime(activity.created_at)}</time><strong>{activity.activity_type.replaceAll("_", " ")}</strong><p>{activity.body || "SEM DETALHES."}</p></article>)}</div></section>
  </div></section></div>;
}

function AppointmentEditor({ appointment, onSave }: { appointment: Appointment; onSave: (patch: { confirmationStatus: string; attendanceStatus: string; enrollmentOutcome: string; surveyStatus: string; welcomeDeliveryStatus: string; note: string }) => Promise<void> }) {
  const [confirmationStatus, setConfirmationStatus] = useState(appointment.confirmation_status); const [attendanceStatus, setAttendanceStatus] = useState(appointment.attendance_status); const [enrollmentOutcome, setEnrollmentOutcome] = useState(appointment.enrollment_outcome); const [surveyStatus, setSurveyStatus] = useState(appointment.survey_status); const [welcomeDeliveryStatus, setWelcomeDeliveryStatus] = useState(appointment.welcome_delivery_status); const [note, setNote] = useState(appointment.note ?? "");
  return <article><header><div><strong>{appointment.class_name_snapshot || appointment.modality_name_snapshot || "AULA EXPERIMENTAL"}</strong><small>{formatDate(appointment.scheduled_on)} · {appointment.starts_at?.slice(0, 5) || "HORÁRIO NÃO INFORMADO"} · {appointment.instructor_name_snapshot || "PROFESSOR NÃO INFORMADO"}</small></div><em>{appointment.booking_kind.replace("REAGENDAMENTO", "REAGENDADO")}</em></header><div><label>CONFIRMAÇÃO<select value={confirmationStatus} onChange={(event) => setConfirmationStatus(event.target.value)}><option value="PENDENTE">PENDENTE</option><option value="CONFIRMADO">CONFIRMADO</option><option value="NAO_CONFIRMADO">NÃO CONFIRMADO</option><option value="NAO_INFORMADO">NÃO INFORMADO</option></select></label><label>PRESENÇA<select value={attendanceStatus} onChange={(event) => setAttendanceStatus(event.target.value)}><option value="AGENDADO">AGENDADO</option><option value="COMPARECEU">COMPARECEU</option><option value="FALTOU">FALTOU</option><option value="CANCELADO">CANCELADO</option><option value="NAO_INFORMADO">NÃO INFORMADO</option></select></label><label>MATRÍCULA<select value={enrollmentOutcome} onChange={(event) => setEnrollmentOutcome(event.target.value)}><option value="PENDENTE">PENDENTE</option><option value="MATRICULOU">MATRICULOU</option><option value="NAO_MATRICULOU">NÃO MATRICULOU</option><option value="NAO_INFORMADO">NÃO INFORMADO</option></select></label><label>PESQUISA<select value={surveyStatus} onChange={(event) => setSurveyStatus(event.target.value)}><option value="PENDENTE">PENDENTE</option><option value="ENVIADA">ENVIADA</option><option value="NAO_ENVIADA">NÃO ENVIADA</option><option value="NAO_INFORMADO">NÃO INFORMADO</option></select></label>{appointment.welcome_video_url ? <label>VÍDEO<select value={welcomeDeliveryStatus} onChange={(event) => setWelcomeDeliveryStatus(event.target.value)}><option value="PENDENTE">PENDENTE</option><option value="ENVIADO">ENVIADO</option><option value="FALHOU">FALHOU</option><option value="DISPENSADO">DISPENSADO</option></select></label> : null}<label className="xd-lead-field-wide">OBSERVAÇÃO<input value={note} onChange={(event) => setNote(event.target.value)} /></label></div>{appointment.welcome_video_url ? <p className="xd-lead-video-state">VÍDEO: {welcomeDeliveryStatus.replaceAll("_", " ")}</p> : null}<button className="xd-secondary" type="button" onClick={() => { void onSave({ confirmationStatus, attendanceStatus, enrollmentOutcome, surveyStatus, welcomeDeliveryStatus, note }); }}><CheckCircle2 size={14} /> REGISTRAR RESULTADO</button></article>;
}

function appointmentSummary(appointments: Appointment[]) { const next = appointments.filter((item) => item.attendance_status === "AGENDADO").sort((left, right) => left.scheduled_on.localeCompare(right.scheduled_on))[0]; return next ? `${formatDate(next.scheduled_on)} · ${next.starts_at?.slice(0, 5) || "A DEFINIR"}` : `${appointments.length} HISTÓRICO(S)`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(`${value}T12:00:00`)); }
function dateTime(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function weekday(value: number) { return ["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"][value] ?? "DIA"; }
