'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,DoorOpen,QrCode,X} from 'lucide-react';
import {mondayOf,shiftDay,occupancyEvents,eventLanes,formatMinutes,type OccupancyRoom,type OccupancyPayload,type OccupancyEvent} from '@/lib/xpace/room-occupancy';
import {teachingApi,schoolToday} from './teaching-client';
import './room-occupancy.css';
const label=(d:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00Z'));
const requests=new Map<string,Promise<OccupancyPayload>>();
function loadWeek(week:string){let pending=requests.get(week);if(!pending){pending=teachingApi<OccupancyPayload>('/api/xpace/aulas?scope=occupation&from='+week);requests.set(week,pending);void pending.finally(()=>{requests.delete(week);}).catch(()=>{});}return pending;}
function WeekControl({week,onChange,roomName}:{week:string;onChange:(week:string)=>void;roomName?:string}){return <div className="ro-week-nav"><button aria-label={'Semana anterior'+(roomName?' de '+roomName:'')} onClick={()=>onChange(shiftDay(week,-7))}><ChevronLeft size={17}/></button><strong>{label(week)} — {label(shiftDay(week,6))}</strong><button aria-label={'Próxima semana'+(roomName?' de '+roomName:'')} onClick={()=>onChange(shiftDay(week,7))}><ChevronRight size={17}/></button><button className="ro-today" onClick={()=>onChange(mondayOf(schoolToday()))}>HOJE</button></div>;}
export default function RoomOccupancy({rooms,independent=false,onPrint}:{rooms:OccupancyRoom[];independent?:boolean;onPrint?:(room:OccupancyRoom)=>void}){
 const[week,setWeek]=useState(()=>mondayOf(schoolToday())),[selected,setSelected]=useState('');
 return <div className="ro-workspace"><div className="ro-toolbar">{!independent?<WeekControl week={week} onChange={setWeek}/>:<p>Explore as semanas de cada sala.</p>}<label>SALA<select aria-label="Filtrar sala" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Todas as salas</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div><div className="ro-legend"><span><i/>Aula da Agenda</span><span><i/>Reserva / locação</span><span><i/>Horário livre</span><small>08h às 22h · Segunda a domingo</small></div>{rooms.filter(r=>!selected||r.id===selected).map(r=><RoomWeek key={r.id} room={r} week={week} independent={independent} onPrint={onPrint}/>)}{!rooms.length?<p className="tw-empty">Cadastre salas para consultar a ocupação.</p>:null}</div>;
}
function RoomWeek({room,week,independent,onPrint}:{room:OccupancyRoom;week:string;independent:boolean;onPrint?:(room:OccupancyRoom)=>void}){
 const[ownWeek,setOwnWeek]=useState(week),[data,setData]=useState<OccupancyPayload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState(true),[detail,setDetail]=useState<OccupancyEvent|null>(null);
 const activeWeek=independent?ownWeek:week;
 useEffect(()=>{let current=true;setLoading(true);setData(null);setError('');void loadWeek(activeWeek).then(p=>{if(current)setData(p);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[activeWeek]);
 const events=data?occupancyEvents(data,room,activeWeek):[],outside=events.filter(e=>e.start<480||e.end>1320);
 return <section className="ro-room" aria-label={'Ocupação de '+room.name}><header><button className="ro-room-title" aria-expanded={open} onClick={()=>setOpen(!open)}><DoorOpen size={19}/><strong>{room.name}</strong><small>{open?'RECOLHER':'EXPANDIR'}</small></button>{onPrint&&room.attendance_token?<button className="tw-text-button" onClick={()=>onPrint(room)}><QrCode size={15}/>IMPRIMIR QR DA SALA</button>:null}</header>{open?<>{independent?<WeekControl week={activeWeek} onChange={setOwnWeek} roomName={room.name}/>:null}{loading?<p className="ro-message" role="status">Carregando ocupação da semana…</p>:error?<p className="ro-message" role="alert">{error} Não foi possível confirmar os horários livres.</p>:<><div className="ro-scroll" tabIndex={0} role="region" aria-label={'Horários da semana de '+room.name}><div className="ro-grid"><aside className="ro-hours"><header>HORÁRIO</header><div>{Array.from({length:15},(_,n)=><time key={n} style={{top:n*48}}>{String(n+8).padStart(2,'0')}:00</time>)}</div></aside>{Array.from({length:7},(_,n)=>{const day=shiftDay(activeWeek,n),dayEvents=events.filter(e=>e.day===day&&e.end>480&&e.start<1320);return <section className={'ro-day'+(day===schoolToday()?' is-today':'')} key={day}><header><span>{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'][new Date(day+'T12:00:00Z').getUTCDay()]}</span><strong>{day.slice(8,10)}/{day.slice(5,7)}</strong></header><div className="ro-timeline">{eventLanes(dayEvents).map(({event,lane,lanes})=><button className="ro-event" key={event.id} title={event.title+' · '+formatMinutes(event.start)+' — '+formatMinutes(event.end)} onClick={()=>setDetail(event)} style={{top:(Math.max(480,event.start)-480)*.8,height:(Math.min(1320,event.end)-Math.max(480,event.start))*.8,left:'calc('+lane/lanes*100+'% + 2px)',width:'calc('+100/lanes+'% - 4px)',background:event.color}}><time>{formatMinutes(event.start)}–{formatMinutes(event.end)}</time><strong>{event.title}</strong></button>)}</div></section>;})}</div></div>{!events.length?<p className="ro-message">Nenhuma ocupação nesta semana.</p>:null}{outside.length?<details className="ro-outside"><summary>{outside.length} ocupação(ões) também fora da faixa de 08h às 22h</summary>{outside.map(e=><p key={e.id}>{label(e.day)} · {formatMinutes(e.start)}–{formatMinutes(e.end)} · {e.title}</p>)}</details>:null}</>}</>:null}{detail?<div className="tw-modal" role="dialog" aria-modal="true" aria-label="Detalhes da ocupação"><section className="ro-detail"><button aria-label="Fechar" onClick={()=>setDetail(null)}><X size={18}/></button><small>{room.name}</small><h3>{detail.title}</h3><p>{label(detail.day)}</p><strong>{formatMinutes(detail.start)} — {formatMinutes(detail.end)}</strong><p>{detail.kind==='class'?'Aula cadastrada na Agenda.':'Horário reservado.'}</p></section></div>:null}</section>;
}
