"use client";

import { DoorOpen, MapPin, Plus } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { supabase } from "@/lib/supabase";

type Room = { id: string; name: string; coverageType: string; active: boolean };

export default function RoomsWorkspace() {
  const [rooms, setRooms] = useState<Room[]>([]); const [draft, setDraft] = useState({ name: "", coverageType: "COBERTO" }); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  useEffect(() => { void loadRooms(); }, []);
  async function request<T>(path: string, init?: RequestInit): Promise<T> { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) throw new Error("SESSÃO NÃO ENCONTRADA."); const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...init?.headers } }); const payload = await response.json().catch(() => ({})) as { success?: boolean; message?: string } & T; if (!response.ok || !payload.success) throw new Error(payload.message || "NÃO FOI POSSÍVEL CONCLUIR A OPERAÇÃO."); return payload; }
  async function loadRooms() { setLoading(true); try { setRooms((await request<{ rooms: Room[] }>("/api/xpace/salas")).rooms); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL CARREGAR AS SALAS."); } finally { setLoading(false); } }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setNotice(""); try { await request("/api/xpace/salas", { method: "POST", body: JSON.stringify({ action: "CREATE_ROOM", room: draft }) }); setDraft({ name: "", coverageType: "COBERTO" }); await loadRooms(); setNotice("SALA CADASTRADA."); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL CADASTRAR A SALA."); } finally { setSaving(false); } }
  async function setActive(room: Room) { setSaving(true); setNotice(""); try { await request("/api/xpace/salas", { method: "PATCH", body: JSON.stringify({ action: "SET_ROOM_ACTIVE", room: { id: room.id, active: !room.active } }) }); await loadRooms(); setNotice(room.active ? "SALA ARQUIVADA." : "SALA REATIVADA."); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL ATUALIZAR A SALA."); } finally { setSaving(false); } }
  return <section className="xd-instructors"><header className="xd-contract-title"><div><span>CONFIGURAÇÕES · ESTRUTURA</span><h1>SALAS.</h1><p>Cadastre as salas que poderão ser ocupadas pelas grades de aula.</p></div></header>{notice ? <p className="xd-feedback">{notice}</p> : null}<div className="xd-instructors-layout"><form className="xd-instructor-form" onSubmit={save}><header><span><MapPin size={18} /> NOVA SALA</span><small>CADASTRO SIMPLES</small></header><label>DESCRIÇÃO *<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required placeholder="EX.: SALA 01" /></label><label>TIPO DE COBERTURA<select value={draft.coverageType} onChange={(event) => setDraft({ ...draft, coverageType: event.target.value })}><option value="COBERTO">COBERTO</option><option value="ABERTO">ABERTO</option><option value="OUTRO">OUTRO</option></select></label><footer><button type="submit" className="xd-primary" disabled={saving}><Plus size={16} /> {saving ? "SALVANDO..." : "CADASTRAR SALA"}</button></footer></form><section className="xd-instructor-list"><header><span><DoorOpen size={18} /> SALAS CADASTRADAS</span><small>{rooms.filter((item) => item.active).length} ATIVA(S)</small></header>{loading ? <p className="xd-agenda-empty">CARREGANDO SALAS...</p> : rooms.length ? rooms.map((room) => <article key={room.id} className={!room.active ? "is-archived" : ""}><span><DoorOpen size={18} /></span><div><strong>{room.name}</strong><small>{room.coverageType}</small></div><button type="button" className="xd-secondary" onClick={() => void setActive(room)} disabled={saving}>{room.active ? "ARQUIVAR" : "REATIVAR"}</button></article>) : <p className="xd-agenda-empty">NENHUMA SALA CADASTRADA.</p>}</section></div></section>;
}
