"use client";

import { DoorOpen, MapPin, Pencil, Plus } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { supabase } from "@/lib/supabase";

type Room = { id: string; name: string; coverageType: string; active: boolean };

export default function RoomsWorkspace() {
  const [rooms, setRooms] = useState<Room[]>([]); const [draft, setDraft] = useState({ name: "", coverageType: "COBERTO" }); const [editingRoomId, setEditingRoomId] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  useEffect(() => { void loadRooms(); }, []);
  async function request<T>(path: string, init?: RequestInit): Promise<T> { const { data } = await supabase.auth.getSession(); const token = data.session?.access_token; if (!token) throw new Error("SESSÃO NÃO ENCONTRADA."); const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...init?.headers } }); const payload = await response.json().catch(() => ({})) as { success?: boolean; message?: string } & T; if (!response.ok || !payload.success) throw new Error(payload.message || "NÃO FOI POSSÍVEL CONCLUIR A OPERAÇÃO."); return payload; }
  async function loadRooms() { setLoading(true); try { setRooms((await request<{ rooms: Room[] }>("/api/xpace/salas")).rooms); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL CARREGAR AS SALAS."); } finally { setLoading(false); } }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setNotice(""); try { const editing = Boolean(editingRoomId); await request("/api/xpace/salas", { method: editing ? "PATCH" : "POST", body: JSON.stringify({ action: editing ? "UPDATE_ROOM" : "CREATE_ROOM", room: { ...draft, id: editingRoomId || undefined } }) }); setDraft({ name: "", coverageType: "COBERTO" }); setEditingRoomId(""); await loadRooms(); setNotice(editing ? "SALA ATUALIZADA." : "SALA CADASTRADA."); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL SALVAR A SALA."); } finally { setSaving(false); } }
  async function setActive(room: Room) { setSaving(true); setNotice(""); try { await request("/api/xpace/salas", { method: "PATCH", body: JSON.stringify({ action: "SET_ROOM_ACTIVE", room: { id: room.id, active: !room.active } }) }); await loadRooms(); setNotice(room.active ? "SALA ARQUIVADA." : "SALA REATIVADA."); } catch (error) { setNotice(error instanceof Error ? error.message : "NÃO FOI POSSÍVEL ATUALIZAR A SALA."); } finally { setSaving(false); } }
  function startEdit(room: Room) { setEditingRoomId(room.id); setDraft({ name: room.name, coverageType: room.coverageType }); setNotice(""); }
  function cancelEdit() { setEditingRoomId(""); setDraft({ name: "", coverageType: "COBERTO" }); }
  return <section className="xd-instructors"><header className="xd-contract-title"><div><span>ADMINISTRATIVO · ESTRUTURA</span><h1>SALAS.</h1><p>Cadastre as salas que poderão ser ocupadas pelas grades de aula.</p></div></header>{notice ? <p className="xd-feedback">{notice}</p> : null}<div className="xd-instructors-layout"><form className="xd-instructor-form" onSubmit={save}><header><span><MapPin size={18} /> {editingRoomId ? "EDITAR SALA" : "NOVA SALA"}</span><small>{editingRoomId ? "ALTERE E SALVE" : "CADASTRO SIMPLES"}</small></header><label>DESCRIÇÃO *<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} required placeholder="EX.: SALA 01" /></label><label>TIPO DE COBERTURA<select value={draft.coverageType} onChange={(event) => setDraft({ ...draft, coverageType: event.target.value })}><option value="COBERTO">COBERTO</option><option value="ABERTO">ABERTO</option><option value="OUTRO">OUTRO</option></select></label><footer>{editingRoomId ? <button type="button" className="xd-secondary" onClick={cancelEdit} disabled={saving}>CANCELAR</button> : null}<button type="submit" className="xd-primary" disabled={saving}>{editingRoomId ? <Pencil size={16} /> : <Plus size={16} />} {saving ? "SALVANDO..." : editingRoomId ? "SALVAR ALTERAÇÕES" : "CADASTRAR SALA"}</button></footer></form><section className="xd-instructor-list"><header><span><DoorOpen size={18} /> SALAS CADASTRADAS</span><small>{rooms.filter((item) => item.active).length} ATIVA(S)</small></header>{loading ? <p className="xd-agenda-empty">CARREGANDO SALAS...</p> : rooms.length ? rooms.map((room) => <article key={room.id} className={!room.active ? "is-archived" : ""}><span><DoorOpen size={18} /></span><div><strong>{room.name}</strong><small>{room.coverageType}</small></div><div className="xd-room-actions"><button type="button" className="xd-secondary" onClick={() => startEdit(room)} disabled={saving}><Pencil size={14} /> EDITAR</button><button type="button" className="xd-secondary" onClick={() => void setActive(room)} disabled={saving}>{room.active ? "ARQUIVAR" : "REATIVAR"}</button></div></article>) : <p className="xd-agenda-empty">NENHUMA SALA CADASTRADA.</p>}</section></div></section>;
}
