-- Run against a seeded database. Every fixture and mutation is rolled back.
-- Explicit negative numbers avoid consuming sale/contract identity sequences.
begin;
do $$
declare c public.xpace_student_contracts; s public.xpace_contract_sales; ch public.xpace_contract_charges;
  cid uuid; paidcid uuid; chargeid uuid; accountid uuid; co uuid; first_effective timestamptz; count_jobs integer;
begin
  select * into c from public.xpace_student_contracts order by created_at desc limit 1;
  if c.id is null then raise exception 'A seeded contract is required'; end if;
  select * into s from public.xpace_contract_sales where contract_id = c.id;
  select * into ch from public.xpace_contract_charges where contract_id = c.id limit 1;
  select id into accountid from public.xpace_payment_accounts where tenant_company_id = c.tenant_company_id limit 1;
  co := c.tenant_company_id;
  c.id := gen_random_uuid(); cid := c.id; c.contract_number := -900000001;
  c.status := 'ATIVO'; c.cancel_effective_on := null; c.cancelled_at := null;
  insert into public.xpace_student_contracts overriding system value select c.*;
  s.id := gen_random_uuid(); s.contract_id := cid; s.sale_number := -900000001;
  s.effective_at := null; s.cancelled_at := null; s.signature_envelope_id := null; s.status := 'CONCLUIDA';
  insert into public.xpace_contract_sales overriding system value select s.*;
  assert (select status = 'EM_PREPARACAO' from public.xpace_contract_sales where id = s.id), 'Unsigned/unpaid creation must not complete the sale';
  update public.xpace_contract_sales set signature_status = 'ASSINADA',status = 'CONCLUIDA' where id = s.id;
  assert (select status = 'EM_PREPARACAO' from public.xpace_contract_sales where id = s.id), 'Signature alone must not complete the sale';
  ch.id := gen_random_uuid(); chargeid := ch.id; ch.contract_id := cid; ch.status := 'ABERTO'; ch.paid_at := null;
  ch.paid_amount_cents := 0; ch.provider_payment_id := 'pay_regression_' || ch.id::text; ch.provider_status := 'PENDING';
  ch.payment_account_id := accountid; ch.provider_cancelled_at := null; ch.cancelled_at := null;
  ch.due_on := current_date - 10;
  insert into public.xpace_contract_charges select ch.*;
  update public.xpace_student_contracts set status = 'ENCERRADO',cancel_effective_on = current_date where id = cid;
  assert (select status = 'CANCELADO' from public.xpace_student_contracts where id = cid), 'Never-paid ending is a cancellation';
  assert (select status = 'CANCELADA' from public.xpace_contract_sales where id = s.id), 'Voided sale must not count';
  assert (select status = 'CANCELADO' from public.xpace_contract_charges where id = chargeid), 'Void must cancel overdue charges too';
  assert exists(select 1 from public.xpace_payment_cancellations where charge_id = chargeid), 'Cancellation intent must persist atomically';
  update public.xpace_contract_sales set signature_status = 'ASSINADA',status = 'CONCLUIDA' where id = s.id;
  assert (select status = 'CANCELADA' from public.xpace_contract_sales where id = s.id), 'Late signature must not complete a void sale';
  perform public.xpace_sync_payment(accountid,jsonb_build_object('id',ch.provider_payment_id,'status','PENDING'),'PAYMENT_UPDATED');
  assert (select status = 'CANCELADO' from public.xpace_contract_charges where id = chargeid), 'Pending event must not reopen';
  select count(*) into count_jobs from public.xpace_claim_cancellations(co,cid);
  assert count_jobs = 1, 'One worker should claim the job';
  select count(*) into count_jobs from public.xpace_claim_cancellations(co,cid);
  assert count_jobs = 0, 'Second worker must not claim leased job';
  perform public.xpace_sync_payment(accountid,jsonb_build_object('id',ch.provider_payment_id,'status','RECEIVED','value',295),'PAYMENT_RECEIVED');
  select effective_at into first_effective from public.xpace_contract_sales where id = s.id;
  assert first_effective is not null, 'Late real receipt must be preserved';
  assert (select status = 'CANCELADO' from public.xpace_student_contracts where id = cid), 'Payment must not reopen the contract';
  perform public.xpace_sync_payment(accountid,jsonb_build_object('id',ch.provider_payment_id,'status','PENDING'),'PAYMENT_UPDATED');
  perform public.xpace_sync_payment(accountid,jsonb_build_object('id',ch.provider_payment_id,'status','PENDING','deleted',true),'PAYMENT_DELETED');
  perform public.xpace_sync_payment(accountid,jsonb_build_object('id',ch.provider_payment_id,'status','RECEIVED','value',295),'PAYMENT_RECEIVED');
  assert (select status = 'RECEBIDO' and paid_amount_cents = 29500 from public.xpace_contract_charges where id = chargeid), 'Stale or repeated events must preserve receipt';
  assert (select effective_at = first_effective and status = 'CONCLUIDA' from public.xpace_contract_sales where id = s.id), 'Commercial history is immutable';

  c.id := gen_random_uuid(); paidcid := c.id; c.contract_number := -900000002;
  insert into public.xpace_student_contracts overriding system value select c.*;
  s.id := gen_random_uuid(); s.contract_id := paidcid; s.sale_number := -900000002;
  insert into public.xpace_contract_sales overriding system value select s.*;
  ch.id := gen_random_uuid(); ch.contract_id := paidcid; ch.provider_payment_id := 'pay_regression_' || ch.id::text;
  ch.status := 'RECEBIDO'; ch.paid_at := now(); ch.paid_amount_cents := 29500;
  insert into public.xpace_contract_charges select ch.*;
  ch.id := gen_random_uuid(); ch.provider_payment_id := 'pay_regression_' || ch.id::text;
  ch.status := 'ABERTO'; ch.paid_at := null; ch.paid_amount_cents := 0; ch.competence_on := ch.competence_on + 31; ch.due_on := current_date + 20;
  insert into public.xpace_contract_charges select ch.*;
  update public.xpace_student_contracts set cancel_effective_on = current_date + 5 where id = paidcid;
  assert (select status = 'ATIVO' from public.xpace_student_contracts where id = paidcid), 'Scheduled end must keep access until its date';
  assert (select status = 'CANCELADO' from public.xpace_contract_charges where id = ch.id), 'Charges due after scheduled ending must be cancelled';
  update public.xpace_student_contracts set status = 'ENCERRADO' where id = paidcid;
  assert (select status = 'ENCERRADO' from public.xpace_student_contracts where id = paidcid), 'Paid contract stays in ending category';
  assert (select status = 'CONCLUIDA' from public.xpace_contract_sales where id = s.id), 'Ending must keep the effective sale';
  assert (select count(*) = 1 from public.xpace_contract_charges where contract_id = paidcid and status = 'RECEBIDO'), 'Past receipts must remain';
  ch.id := gen_random_uuid(); ch.provider_payment_id := null; ch.status := 'ABERTO'; ch.competence_on := ch.competence_on + 31;
  insert into public.xpace_contract_charges select ch.*;
  assert (select status = 'CANCELADO' from public.xpace_contract_charges where id = ch.id), 'Stale generation must not recreate collectible charges';
  assert not has_function_privilege('anon','public.xpace_sync_payment(uuid,jsonb,text)','EXECUTE'), 'Anonymous must not sync payments';
  assert not has_function_privilege('authenticated','public.xpace_claim_cancellations(uuid,uuid)','EXECUTE'), 'Clients must not claim jobs';
end $$;
rollback;
select 'All lifecycle assertions passed; test records rolled back.' as result;
